apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sentries.sentry.redhat.com
spec:
  group: sentry.redhat.com
  names:
    kind: Sentry
    listKind: SentryList
    plural: sentries
    singular: sentry
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            postgresDB:
              description: PostgresDB is the database within postgres we're using
              type: string
            postgresHost:
              description: PostgresHost is the name of server running postgres
              type: string
            postgresPasswordKey:
              description: 'PostgresPasswordKey is the key inside the sentry secret
                holding the password to connect to the database (defaults: SENTRY_DB_PASSWORD)'
              type: string
            postgresPort:
              description: 'PostgresPort is the port on which the database server
                is listening (defaults: 5432)'
              format: int64
              type: integer
            postgresUser:
              description: PostgresUser is the name of the secret containing the database
                username
              type: string
            redisDB:
              description: 'RedisDB is the name of the redis instance we''re using
                (defaults: "0")'
              type: string
            redisHost:
              description: RedisHost is the name of the server running redis
              type: string
            redisPort:
              description: 'RedisPort is the port on which the redis server is listening
                (defaults: 6379)'
              format: int64
              type: integer
            sentryEnvironment:
              description: 'SentryEnvironment is the environment this sentry cluster
                belongs to (defaults: production)'
              type: string
            sentryImage:
              description: 'SentryImage is the image of sentry we are running (defaults:
                docker.io/sentry:latest)'
              type: string
            sentrySecret:
              description: SentrySecret is the secret holding the sentry-specific
                secret config values
              type: string
            sentrySecretKeyKey:
              description: 'SentrySecretKeyKey is the key inside the sentry secret
                holding the salt hash string for cryptography (defaults: SENTRY_SECRET_KEY)'
              type: string
            sentrySuperUserEmailKey:
              description: 'SentrySuperUserEmailKey is the key inside the sentry secret
                holding the superuser''s email address (defaults: "SENTRY_SU_EMAIL")'
              type: string
            sentrySuperUserPasswordKey:
              description: 'SentrySuperUserPasswordKey is the key inside the sentry
                secret holding the superuser''s password (defaults: "SENTRY_SU_PASSWORD")'
              type: string
            sentryWebReplicas:
              description: 'SentryWebReplicas is the number of web workers to spawn
                (defaults: 2)'
              format: int64
              type: integer
            sentryWorkers:
              description: 'SentryWorkers is the number of async workers to spawn
                (defaults: 3)'
              format: int64
              type: integer
          required:
          - sentrySecret
          - postgresHost
          - postgresDB
          - postgresUser
          - redisHost
          type: object
        status:
          properties:
            status:
              type: string
          required:
          - status
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
