---
apiVersion: v1
data:
  command.sh: |
    /sbin/apk add redis postgresql curl
    /bin/echo "Going to sleep for 12h now"
    /bin/sleep 12h
    /bin/echo "Good bye."
kind: ConfigMap
metadata:
  name: control
  labels:
    app: control-pod

---
apiVersion: v1
kind: Pod
metadata:
  name: control
  labels:
    app: control-pod
spec:
  restartPolicy: Never
  containers:
  - name: admin
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    args:
      - /bin/sh
      - -c
      - /opt/bin/command.sh
    env:
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          key: POSTGRES_USER
          name: postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: POSTGRES_PASSWORD
          name: postgres
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          key: POSTGRES_DB
          name: postgres
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 512Mi
    volumeMounts:
    - mountPath: /opt/bin
      name: command
  volumes:
  - name: command
    configMap:
      name: control
      defaultMode: 0755
      items:
        - key: command.sh
          path: command.sh
...
