---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.5-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /data
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SENTRY_DB_PASSWORD
              name: sentry
        - name: POSTGRES_DB
          value: sentry
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres
...
