// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/sd-hackday-sentry/sentry-operator/pkg/apis/sentry/v1alpha1.Sentry":       schema_pkg_apis_sentry_v1alpha1_Sentry(ref),
		"github.com/sd-hackday-sentry/sentry-operator/pkg/apis/sentry/v1alpha1.SentrySpec":   schema_pkg_apis_sentry_v1alpha1_SentrySpec(ref),
		"github.com/sd-hackday-sentry/sentry-operator/pkg/apis/sentry/v1alpha1.SentryStatus": schema_pkg_apis_sentry_v1alpha1_SentryStatus(ref),
	}
}

func schema_pkg_apis_sentry_v1alpha1_Sentry(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Sentry is the Schema for the sentries API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/sd-hackday-sentry/sentry-operator/pkg/apis/sentry/v1alpha1.SentrySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/sd-hackday-sentry/sentry-operator/pkg/apis/sentry/v1alpha1.SentryStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/sd-hackday-sentry/sentry-operator/pkg/apis/sentry/v1alpha1.SentrySpec", "github.com/sd-hackday-sentry/sentry-operator/pkg/apis/sentry/v1alpha1.SentryStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_sentry_v1alpha1_SentrySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SentrySpec defines the desired state of Sentry",
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Description: "Name is the distinct name of the Sentry service we're running",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"sentryVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "SentryVersion is the version of sentry we are running",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"postgresHost": {
						SchemaProps: spec.SchemaProps{
							Description: "PostgresHost is the name of server running postgres",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"postgresPort": {
						SchemaProps: spec.SchemaProps{
							Description: "PostgresPort is the port on which the database server is listening",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"postgresDB": {
						SchemaProps: spec.SchemaProps{
							Description: "PostgresDB is the database within postgres we're using",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"postgresUser": {
						SchemaProps: spec.SchemaProps{
							Description: "PostgresUser is the name of the secret containing the database username",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"postgresPassword": {
						SchemaProps: spec.SchemaProps{
							Description: "PostgresPassword is the name of the secret containing the database password",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"redisHost": {
						SchemaProps: spec.SchemaProps{
							Description: "RedisHost is the name of the server running redis",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"redisPort": {
						SchemaProps: spec.SchemaProps{
							Description: "RedisPort is the port on which the redis server is listening",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"redisDB": {
						SchemaProps: spec.SchemaProps{
							Description: "RedisDB is the name of the redis instance we're using",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"name", "sentryVersion", "postgresHost", "postgresPort", "postgresDB", "postgresUser", "postgresPassword", "redisHost", "redisPort", "redisDB"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_sentry_v1alpha1_SentryStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SentryStatus defines the observed state of Sentry",
				Properties: map[string]spec.Schema{
					"status": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"status"},
			},
		},
		Dependencies: []string{},
	}
}
